### ISSUE TITLE
cat: /etc/*release: No such file or directory

### ISSUE THREAD

**Issue by HumanFact** [JustinTimperio/gdelt-diff#3]
I receive this warning while installing.

**Comment by JustinTimperio** [comment]
What OS are you currently on? Can you please send the full output of the log as well?

**Comment by HumanFact** [comment]
Sure... Thanks for prompt answer.

**Comment by HumanFact** [comment]
$ curl https://raw.githubusercontent.com/JustinTimperio/gdelt-diff/master/build/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1760  100  1760    0     0  34509      0 --:--:-- --:--:-- --:--:-- 34509
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
cat: /etc/*release: No such file or directory
Is Not Supported!

**Comment by HumanFact** [comment]
macOS Catalina 10.15.7

**Comment by JustinTimperio** [comment]
Sorry but only Linux(Debian, RHL, Arch) is supported at this time. The python scripts still may work for you but this project is designed for servers, not desktops.
